<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class NotificationTemplateMultilingualSeeder extends Seeder
{
    public function run()
    {
        // ✅ Supprimer tous les anciens templates
        DB::table('notification_templates')->truncate();

        $templates = [
            // ==================== GUIDES ====================
            [
                'type' => 'guide_created',
                'name' => 'guide_created',
                'title_template' => 'Guide Created',
                'title_template_ar' => 'تم إنشاء الدليل',
                'message_template' => 'Your guide "{{guide_title}}" has been successfully created',
                'message_template_ar' => 'تم إنشاء دليلك "{{guide_title}}" بنجاح',
                'icon' => 'check_circle',
                'color' => '#4CAF50',
                'sound' => 'success',
            ],
            [
                'type' => 'guide_published',
                'name' => 'guide_published',
                'title_template' => 'New Guide Published',
                'title_template_ar' => 'دليل جديد',
                'message_template' => 'New guide "{{guide_title}}" by {{author_name}} is now available',
                'message_template_ar' => 'دليل جديد "{{guide_title}}" من {{author_name}} متاح الآن',
                'icon' => 'book',
                'color' => '#2196F3',
                'sound' => 'default',
            ],
            [
                'type' => 'new_guide_published',
                'name' => 'new_guide_published',
                'title_template' => 'Guide Created',
                'title_template_ar' => 'تم إنشاء الدليل',
                'message_template' => 'Your guide "{{guide_title}}" has been successfully created',
                'message_template_ar' => 'تم إنشاء دليلك "{{guide_title}}" بنجاح',
                'icon' => 'library_books',
                'color' => '#4CAF50',
                'sound' => 'success',
            ],
            [
                'type' => 'guide_new_like',
                'name' => 'guide_new_like',
                'title_template' => 'New Guide Like',
                'title_template_ar' => 'إعجاب جديد بالدليل',
                'message_template' => '{{liker_name}} liked your guide "{{guide_title}}"',
                'message_template_ar' => '{{liker_name}} أعجب بدليلك "{{guide_title}}"',
                'icon' => 'favorite',
                'color' => '#E91E63',
                'sound' => 'default',
            ],
            [
                'type' => 'guide_new_comment',
                'name' => 'guide_new_comment',
                'title_template' => 'New Guide Comment',
                'title_template_ar' => 'تعليق جديد على الدليل',
                'message_template' => '{{commenter_name}} commented on "{{guide_title}}"',
                'message_template_ar' => '{{commenter_name}} علق على "{{guide_title}}"',
                'icon' => 'comment',
                'color' => '#2196F3',
                'sound' => 'default',
            ],

            // ==================== EVENTS ====================
            [
                'type' => 'event_created',
                'name' => 'event_created',
                'title_template' => 'Event Created',
                'title_template_ar' => 'تم إنشاء الحدث',
                'message_template' => 'Your event "{{event_title}}" has been successfully created',
                'message_template_ar' => 'تم إنشاء حدثك "{{event_title}}" بنجاح',
                'icon' => 'add_circle',
                'color' => '#4CAF50',
                'sound' => 'success',
            ],
            [
                'type' => 'event_updated',
                'name' => 'event_updated',
                'title_template' => 'Event Updated',
                'title_template_ar' => 'تم تحديث الحدث',
                'message_template' => 'Event "{{event_title}}" has been updated',
                'message_template_ar' => 'تم تحديث الحدث "{{event_title}}"',
                'icon' => 'update',
                'color' => '#2196F3',
                'sound' => 'default',
            ],
            [
                'type' => 'event_reminder',
                'name' => 'event_reminder',
                'title_template' => 'Event Reminder',
                'title_template_ar' => 'تذكير بالحدث',
                'message_template' => 'Event "{{event_title}}" starts tomorrow at {{event_location}}',
                'message_template_ar' => 'يبدأ الحدث "{{event_title}}" غداً في {{event_location}}',
                'icon' => 'notifications',
                'color' => '#FF9800',
                'sound' => 'default',
            ],
            [
                'type' => 'event_starting_soon',
                'name' => 'event_starting_soon',
                'title_template' => 'Event Starting Soon',
                'title_template_ar' => 'الحدث يبدأ قريباً',
                'message_template' => 'Event "{{event_title}}" starts in 1 hour',
                'message_template_ar' => 'يبدأ الحدث "{{event_title}}" خلال ساعة',
                'icon' => 'alarm',
                'color' => '#FF9800',
                'sound' => 'default',
            ],
            [
                'type' => 'event_cancelled',
                'name' => 'event_cancelled',
                'title_template' => 'Event Cancelled',
                'title_template_ar' => 'تم إلغاء الحدث',
                'message_template' => 'Event "{{event_title}}" has been cancelled',
                'message_template_ar' => 'تم إلغاء الحدث "{{event_title}}"',
                'icon' => 'cancel',
                'color' => '#F44336',
                'sound' => 'default',
            ],

            // ==================== LISTINGS ====================
            [
                'type' => 'listing_created',
                'name' => 'listing_created',
                'title_template' => 'Listing Created',
                'title_template_ar' => 'تم إنشاء الإعلان',
                'message_template' => 'Your listing "{{listing_title}}" has been created and is under review',
                'message_template_ar' => 'تم إنشاء إعلانك "{{listing_title}}" وهو قيد المراجعة',
                'icon' => 'add_business',
                'color' => '#2196F3',
                'sound' => 'default',
            ],
            [
                'type' => 'listing_approved',
                'name' => 'listing_approved',
                'title_template' => 'Listing Approved',
                'title_template_ar' => 'تم قبول الإعلان',
                'message_template' => 'Your listing "{{listing_title}}" is now live',
                'message_template_ar' => 'إعلانك "{{listing_title}}" أصبح نشطاً الآن',
                'icon' => 'check_circle',
                'color' => '#4CAF50',
                'sound' => 'success',
            ],
            [
                'type' => 'listing_rejected',
                'name' => 'listing_rejected',
                'title_template' => 'Listing Rejected',
                'title_template_ar' => 'تم رفض الإعلان',
                'message_template' => 'Your listing "{{listing_title}}" was rejected. Reason: {{rejection_reason}}',
                'message_template_ar' => 'تم رفض إعلانك "{{listing_title}}". السبب: {{rejection_reason}}',
                'icon' => 'cancel',
                'color' => '#F44336',
                'sound' => 'default',
            ],
            [
                'type' => 'listing_message',
                'name' => 'listing_message',
                'title_template' => 'New Message',
                'title_template_ar' => 'رسالة جديدة',
                'message_template' => '{{sender_name}} sent you a message about "{{listing_title}}"',
                'message_template_ar' => 'أرسل لك {{sender_name}} رسالة حول "{{listing_title}}"',
                'icon' => 'message',
                'color' => '#2196F3',
                'sound' => 'default',
            ],
            [
                'type' => 'listing_sold',
                'name' => 'listing_sold',
                'title_template' => 'Listing Sold',
                'title_template_ar' => 'تم بيع الإعلان',
                'message_template' => 'Your listing "{{listing_title}}" has been sold',
                'message_template_ar' => 'تم بيع إعلانك "{{listing_title}}"',
                'icon' => 'monetization_on',
                'color' => '#4CAF50',
                'sound' => 'success',
            ],

            // ==================== SOOM (AUCTIONS) ====================
            [
                'type' => 'soom_bid',
                'name' => 'soom_bid',
                'title_template' => 'New Bid Placed',
                'title_template_ar' => 'عرض جديد',
                'message_template' => '{{bidder_name}} placed a bid of {{bid_amount}} on "{{soom_title}}"',
                'message_template_ar' => 'قدم {{bidder_name}} عرضاً بقيمة {{bid_amount}} على "{{soom_title}}"',
                'icon' => 'gavel',
                'color' => '#FF9800',
                'sound' => 'default',
            ],
            [
                'type' => 'soom_outbid',
                'name' => 'soom_outbid',
                'title_template' => 'You Were Outbid',
                'title_template_ar' => 'تم تجاوز عرضك',
                'message_template' => 'Someone bid {{new_bid_amount}} on "{{soom_title}}"',
                'message_template_ar' => 'قدم شخص عرضاً بقيمة {{new_bid_amount}} على "{{soom_title}}"',
                'icon' => 'trending_up',
                'color' => '#F44336',
                'sound' => 'default',
            ],
            [
                'type' => 'soom_won',
                'name' => 'soom_won',
                'title_template' => 'Auction Won!',
                'title_template_ar' => 'مبروك! فزت بالمزاد',
                'message_template' => 'You won the auction for "{{soom_title}}" with {{winning_bid}}',
                'message_template_ar' => 'فزت بالمزاد لـ "{{soom_title}}" بعرض {{winning_bid}}',
                'icon' => 'emoji_events',
                'color' => '#FFD700',
                'sound' => 'success',
            ],
            [
                'type' => 'soom_lost',
                'name' => 'soom_lost',
                'title_template' => 'Auction Lost',
                'title_template_ar' => 'خسرت المزاد',
                'message_template' => 'You lost the auction for "{{soom_title}}"',
                'message_template_ar' => 'خسرت المزاد لـ "{{soom_title}}"',
                'icon' => 'sentiment_dissatisfied',
                'color' => '#9E9E9E',
                'sound' => 'default',
            ],
            [
                'type' => 'soom_ending_soon',
                'name' => 'soom_ending_soon',
                'title_template' => 'Auction Ending Soon',
                'title_template_ar' => 'المزاد ينتهي قريباً',
                'message_template' => 'Auction for "{{soom_title}}" ends in 1 hour',
                'message_template_ar' => 'ينتهي المزاد لـ "{{soom_title}}" خلال ساعة',
                'icon' => 'timer',
                'color' => '#FF9800',
                'sound' => 'default',
            ],

            // ==================== ORDERS ====================
            [
                'type' => 'order_created',
                'name' => 'order_created',
                'title_template' => 'Order Created',
                'title_template_ar' => 'تم إنشاء الطلب',
                'message_template' => 'Your order #{{order_number}} has been created',
                'message_template_ar' => 'تم إنشاء طلبك رقم {{order_number}}',
                'icon' => 'shopping_cart',
                'color' => '#4CAF50',
                'sound' => 'default',
            ],
            [
                'type' => 'order_status_confirmed',
                'name' => 'order_status_confirmed',
                'title_template' => 'Order Confirmed',
                'title_template_ar' => 'تم تأكيد الطلب',
                'message_template' => 'Your order #{{order_number}} has been confirmed',
                'message_template_ar' => 'تم تأكيد طلبك رقم {{order_number}}',
                'icon' => 'check_circle',
                'color' => '#4CAF50',
                'sound' => 'success',
            ],
            [
                'type' => 'order_shipped',
                'name' => 'order_shipped',
                'title_template' => 'Order Shipped',
                'title_template_ar' => 'تم شحن الطلب',
                'message_template' => 'Your order #{{order_number}} has been shipped. Tracking: {{tracking_number}}',
                'message_template_ar' => 'تم شحن طلبك رقم {{order_number}}. رقم التتبع: {{tracking_number}}',
                'icon' => 'local_shipping',
                'color' => '#2196F3',
                'sound' => 'default',
            ],
            [
                'type' => 'order_status_delivered',
                'name' => 'order_status_delivered',
                'title_template' => 'Order Delivered',
                'title_template_ar' => 'تم توصيل الطلب',
                'message_template' => 'Your order #{{order_number}} has been delivered',
                'message_template_ar' => 'تم توصيل طلبك رقم {{order_number}}',
                'icon' => 'done_all',
                'color' => '#4CAF50',
                'sound' => 'success',
            ],
            [
                'type' => 'order_cancelled',
                'name' => 'order_cancelled',
                'title_template' => 'Order Cancelled',
                'title_template_ar' => 'تم إلغاء الطلب',
                'message_template' => 'Your order #{{order_number}} has been cancelled',
                'message_template_ar' => 'تم إلغاء طلبك رقم {{order_number}}',
                'icon' => 'cancel',
                'color' => '#F44336',
                'sound' => 'default',
            ],

            // ==================== PAYMENTS ====================
            [
                'type' => 'payment_success',
                'name' => 'payment_success',
                'title_template' => 'Payment Successful',
                'title_template_ar' => 'تم الدفع بنجاح',
                'message_template' => 'Payment of {{amount}} for order #{{order_number}} was successful',
                'message_template_ar' => 'تم دفع {{amount}} للطلب رقم {{order_number}} بنجاح',
                'icon' => 'verified',
                'color' => '#4CAF50',
                'sound' => 'success',
            ],
            [
                'type' => 'payment_failed',
                'name' => 'payment_failed',
                'title_template' => 'Payment Failed',
                'title_template_ar' => 'فشل الدفع',
                'message_template' => 'Payment of {{amount}} failed. Please try again',
                'message_template_ar' => 'فشل دفع {{amount}}. يرجى المحاولة مرة أخرى',
                'icon' => 'error',
                'color' => '#F44336',
                'sound' => 'default',
            ],
            [
                'type' => 'refund_processed',
                'name' => 'refund_processed',
                'title_template' => 'Refund Processed',
                'title_template_ar' => 'تم معالجة الاسترداد',
                'message_template' => 'Refund of {{amount}} for order #{{order_number}} has been processed',
                'message_template_ar' => 'تم معالجة استرداد {{amount}} للطلب رقم {{order_number}}',
                'icon' => 'account_balance_wallet',
                'color' => '#4CAF50',
                'sound' => 'success',
            ],

            // ==================== POI ====================
            [
                'type' => 'poi_nearby',
                'name' => 'poi_nearby',
                'title_template' => 'Nearby Point of Interest',
                'title_template_ar' => 'نقطة اهتمام قريبة',
                'message_template' => '{{poi_name}} is {{distance}}km away from you',
                'message_template_ar' => '{{poi_name}} يبعد {{distance}} كم عنك',
                'icon' => 'place',
                'color' => '#2196F3',
                'sound' => 'default',
            ],

            // ==================== ROUTES ====================
            [
                'type' => 'route_warning',
                'name' => 'route_warning',
                'title_template' => 'Route Warning',
                'title_template_ar' => 'تحذير بشأن المسار',
                'message_template' => 'Warning reported on route',
                'message_template_ar' => 'تم الإبلاغ عن تحذير في المسار',
                'icon' => 'warning',
                'color' => '#FF9800',
                'sound' => 'default',
            ],
        ];

        foreach ($templates as $template) {
            DB::table('notification_templates')->insert([
                'type' => $template['type'],
                'name' => $template['name'],
                'title_template' => $template['title_template'],
                'title_template_ar' => $template['title_template_ar'],
                'message_template' => $template['message_template'],
                'message_template_ar' => $template['message_template_ar'],
                'icon' => $template['icon'],
                'color' => $template['color'],
                'sound' => $template['sound'],
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}