<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\NotificationTemplate;

class NotificationTemplateSeeder extends Seeder
{
    public function run(): void
    {
        $templates = [
            // Listings
            [
                'type' => 'listing_approved',
                'name' => 'Listing Approved',
                'description' => 'Sent when a listing is approved',
                'title_template' => '✅ Listing Approved | تمت الموافقة على الإعلان',
                'message_template' => 'Your listing "{{listing_title}}" has been approved and is now visible. | تمت الموافقة على إعلانك "{{listing_title}}" وهو الآن مرئي.',
                'variables' => ['listing_title', 'listing_id'],
                'icon' => 'check_circle',
                'color' => '#4CAF50',
                'sound' => 'default',
            ],
            [
                'type' => 'listing_rejected',
                'name' => 'Listing Rejected',
                'description' => 'Sent when a listing is rejected',
                'title_template' => '❌ Listing Rejected | تم رفض الإعلان',
                'message_template' => 'Your listing "{{listing_title}}" has been rejected. Reason: {{reason}} | تم رفض إعلانك "{{listing_title}}". السبب: {{reason}}',
                'variables' => ['listing_title', 'listing_id', 'reason'],
                'icon' => 'cancel',
                'color' => '#F44336',
                'sound' => 'default',
            ],
            [
                'type' => 'listing_expired',
                'name' => 'Listing Expired',
                'description' => 'Sent when a listing expires',
                'title_template' => '⏰ Listing Expired | انتهت صلاحية الإعلان',
                'message_template' => 'Your listing "{{listing_title}}" has expired. Renew it to continue. | انتهت صلاحية إعلانك "{{listing_title}}". قم بتجديده للمتابعة.',
                'variables' => ['listing_title', 'listing_id'],
                'icon' => 'schedule',
                'color' => '#FF9800',
                'sound' => 'default',
            ],
            [
                'type' => 'listing_sold',
                'name' => 'Listing Sold',
                'description' => 'Sent when a listing is marked as sold',
                'title_template' => '🎉 Congratulations! | تهانينا!',
                'message_template' => 'Your listing "{{listing_title}}" has been sold for {{price}} MAD. | تم بيع إعلانك "{{listing_title}}" بسعر {{price}} درهم.',
                'variables' => ['listing_title', 'listing_id', 'price'],
                'icon' => 'celebration',
                'color' => '#4CAF50',
                'sound' => 'success',
            ],

            // Auctions
            [
                'type' => 'bid_placed',
                'name' => 'New Bid Placed',
                'description' => 'Sent when someone places a bid',
                'title_template' => '💰 New Bid | مزايدة جديدة',
                'message_template' => '{{bidder_name}} placed a bid of {{amount}} MAD on "{{listing_title}}". | قام {{bidder_name}} بمزايدة بمبلغ {{amount}} درهم على "{{listing_title}}".',
                'variables' => ['bidder_name', 'amount', 'listing_title', 'listing_id'],
                'icon' => 'gavel',
                'color' => '#2196F3',
                'sound' => 'default',
            ],
            [
                'type' => 'bid_accepted',
                'name' => 'Bid Accepted',
                'description' => 'Sent when a bid is accepted',
                'title_template' => '🎉 Bid Accepted | تم قبول المزايدة',
                'message_template' => 'Your bid of {{amount}} MAD on "{{listing_title}}" has been accepted! | تم قبول مزايدتك بمبلغ {{amount}} درهم على "{{listing_title}}"!',
                'variables' => ['amount', 'listing_title', 'listing_id'],
                'icon' => 'check_circle',
                'color' => '#4CAF50',
                'sound' => 'success',
            ],
            [
                'type' => 'bid_rejected',
                'name' => 'Bid Rejected',
                'description' => 'Sent when a bid is rejected',
                'title_template' => '❌ Bid Rejected | تم رفض المزايدة',
                'message_template' => 'Your bid of {{amount}} MAD on "{{listing_title}}" has been rejected. | تم رفض مزايدتك بمبلغ {{amount}} درهم على "{{listing_title}}".',
                'variables' => ['amount', 'listing_title', 'listing_id'],
                'icon' => 'cancel',
                'color' => '#F44336',
                'sound' => 'default',
            ],
            [
                'type' => 'bid_outbid',
                'name' => 'Outbid',
                'description' => 'Sent when you are outbid',
                'title_template' => '⚠️ Outbid | تم المزايدة عليك',
                'message_template' => 'You have been outbid on "{{listing_title}}". New bid: {{new_amount}} MAD. | تمت المزايدة عليك في "{{listing_title}}". المزايدة الجديدة: {{new_amount}} درهم.',
                'variables' => ['listing_title', 'listing_id', 'new_amount'],
                'icon' => 'trending_up',
                'color' => '#FF9800',
                'sound' => 'default',
            ],
            [
                'type' => 'auction_ending_soon',
                'name' => 'Auction Ending Soon',
                'description' => 'Sent when auction ends in 1 hour',
                'title_template' => '⏰ Auction Ending Soon | المزاد ينتهي قريباً',
                'message_template' => 'The auction for "{{listing_title}}" ends in {{time_left}}. | المزاد على "{{listing_title}}" ينتهي في {{time_left}}.',
                'variables' => ['listing_title', 'listing_id', 'time_left'],
                'icon' => 'schedule',
                'color' => '#FF9800',
                'sound' => 'default',
            ],

            // Payments
            [
                'type' => 'payment_success',
                'name' => 'Payment Successful',
                'description' => 'Sent after successful payment',
                'title_template' => '✅ Payment Successful | تم الدفع بنجاح',
                'message_template' => 'Your payment of {{amount}} MAD has been confirmed. Thank you! | تم تأكيد دفعتك بمبلغ {{amount}} درهم. شكراً لك!',
                'variables' => ['amount', 'order_id'],
                'icon' => 'payments',
                'color' => '#4CAF50',
                'sound' => 'success',
            ],
            [
                'type' => 'payment_failed',
                'name' => 'Payment Failed',
                'description' => 'Sent after failed payment',
                'title_template' => '❌ Payment Failed | فشل الدفع',
                'message_template' => 'Your payment of {{amount}} MAD has failed. Please try again. | فشلت عملية الدفع بمبلغ {{amount}} درهم. يرجى المحاولة مرة أخرى.',
                'variables' => ['amount', 'order_id', 'reason'],
                'icon' => 'error',
                'color' => '#F44336',
                'sound' => 'error',
            ],
            [
                'type' => 'payment_pending',
                'name' => 'Payment Pending',
                'description' => 'Sent when payment is pending',
                'title_template' => '⏳ Payment Pending | الدفع قيد الانتظار',
                'message_template' => 'Your payment of {{amount}} MAD is being processed. | دفعتك بمبلغ {{amount}} درهم قيد المعالجة.',
                'variables' => ['amount', 'order_id'],
                'icon' => 'hourglass_empty',
                'color' => '#FF9800',
                'sound' => 'default',
            ],

            // Wishlist
            [
                'type' => 'wishlist_price_drop',
                'name' => 'Price Drop',
                'description' => 'Sent when wishlist item price drops',
                'title_template' => '💰 Price Drop! | انخفاض السعر!',
                'message_template' => '"{{listing_title}}" is now {{new_price}} MAD ({{discount}}% off). | "{{listing_title}}" الآن بسعر {{new_price}} درهم (خصم {{discount}}٪).',
                'variables' => ['listing_title', 'listing_id', 'old_price', 'new_price', 'discount'],
                'icon' => 'trending_down',
                'color' => '#4CAF50',
                'sound' => 'default',
            ],
            [
                'type' => 'wishlist_item_sold',
                'name' => 'Wishlist Item Sold',
                'description' => 'Sent when wishlist item is sold',
                'title_template' => '😢 Item Sold | تم بيع العنصر',
                'message_template' => '"{{listing_title}}" from your wishlist has been sold. | تم بيع "{{listing_title}}" من قائمة رغباتك.',
                'variables' => ['listing_title', 'listing_id'],
                'icon' => 'remove_shopping_cart',
                'color' => '#FF9800',
                'sound' => 'default',
            ],

            // Messages
            [
                'type' => 'new_message',
                'name' => 'New Message',
                'description' => 'Sent when receiving a new message',
                'title_template' => '💬 New Message | رسالة جديدة',
                'message_template' => '{{sender_name}} sent you a message: "{{message_preview}}" | أرسل لك {{sender_name}} رسالة: "{{message_preview}}"',
                'variables' => ['sender_name', 'message_preview', 'chat_id'],
                'icon' => 'message',
                'color' => '#2196F3',
                'sound' => 'message',
            ],

            // Guides
            [
                'type' => 'new_guide_published',
                'name' => 'New Guide Published',
                'description' => 'Sent when a new guide is published',
                'title_template' => '📚 New Guide | دليل جديد',
                'message_template' => 'New guide published: "{{guide_title}}" | تم نشر دليل جديد: "{{guide_title}}"',
                'variables' => ['guide_title', 'guide_id'],
                'icon' => 'auto_stories',
                'color' => '#9C27B0',
                'sound' => 'default',
            ],
            [
                'type' => 'guide_comment',
                'name' => 'Guide Comment',
                'description' => 'Sent when someone comments on your guide',
                'title_template' => '💭 New Comment | تعليق جديد',
                'message_template' => '{{commenter_name}} commented on your guide "{{guide_title}}". | علق {{commenter_name}} على دليلك "{{guide_title}}".',
                'variables' => ['commenter_name', 'guide_title', 'guide_id', 'comment_preview'],
                'icon' => 'comment',
                'color' => '#2196F3',
                'sound' => 'default',
            ],
            [
                'type' => 'guide_like',
                'name' => 'Guide Like',
                'description' => 'Sent when someone likes your guide',
                'title_template' => '❤️ New Like | إعجاب جديد',
                'message_template' => '{{liker_name}} liked your guide "{{guide_title}}". | أعجب {{liker_name}} بدليلك "{{guide_title}}".',
                'variables' => ['liker_name', 'guide_title', 'guide_id'],
                'icon' => 'favorite',
                'color' => '#E91E63',
                'sound' => 'default',
            ],

            // Events
            [
                'type' => 'event_reminder',
                'name' => 'Event Reminder',
                'description' => 'Sent before an event starts',
                'title_template' => '📅 Event Reminder | تذكير بالحدث',
                'message_template' => '"{{event_title}}" starts {{time_until}}. | يبدأ "{{event_title}}" في {{time_until}}.',
                'variables' => ['event_title', 'event_id', 'time_until', 'event_date'],
                'icon' => 'event',
                'color' => '#FF5722',
                'sound' => 'default',
            ],
            [
                'type' => 'event_updated',
                'name' => 'Event Updated',
                'description' => 'Sent when event details are updated',
                'title_template' => '📝 Event Updated | تم تحديث الحدث',
                'message_template' => 'The event "{{event_title}}" has been updated. Check the new details. | تم تحديث الحدث "{{event_title}}". تحقق من التفاصيل الجديدة.',
                'variables' => ['event_title', 'event_id'],
                'icon' => 'edit_calendar',
                'color' => '#FF9800',
                'sound' => 'default',
            ],
            [
                'type' => 'event_cancelled',
                'name' => 'Event Cancelled',
                'description' => 'Sent when an event is cancelled',
                'title_template' => '❌ Event Cancelled | تم إلغاء الحدث',
                'message_template' => 'The event "{{event_title}}" has been cancelled. | تم إلغاء الحدث "{{event_title}}".',
                'variables' => ['event_title', 'event_id', 'reason'],
                'icon' => 'event_busy',
                'color' => '#F44336',
                'sound' => 'default',
            ],

            // POI
            [
                'type' => 'poi_review',
                'name' => 'POI Review',
                'description' => 'Sent when someone reviews your POI',
                'title_template' => '⭐ New Review | تقييم جديد',
                'message_template' => '{{reviewer_name}} reviewed "{{poi_name}}" ({{rating}}/5 stars). | قام {{reviewer_name}} بتقييم "{{poi_name}}" ({{rating}}/5 نجوم).',
                'variables' => ['reviewer_name', 'poi_name', 'poi_id', 'rating'],
                'icon' => 'star',
                'color' => '#FFC107',
                'sound' => 'default',
            ],
            [
                'type' => 'new_poi_nearby',
                'name' => 'New POI Nearby',
                'description' => 'Sent when a new POI is added nearby',
                'title_template' => '📍 New Place Nearby | مكان جديد قريب منك',
                'message_template' => 'New place "{{poi_name}}" added {{distance}} km from you. | تمت إضافة مكان جديد "{{poi_name}}" على بعد {{distance}} كم منك.',
                'variables' => ['poi_name', 'poi_id', 'distance'],
                'icon' => 'place',
                'color' => '#4CAF50',
                'sound' => 'default',
            ],

            // Routes
            [
                'type' => 'route_comment',
                'name' => 'Route Comment',
                'description' => 'Sent when someone comments on your route',
                'title_template' => '💭 Route Comment | تعليق على المسار',
                'message_template' => '{{commenter_name}} commented on your route "{{route_name}}". | علق {{commenter_name}} على مسارك "{{route_name}}".',
                'variables' => ['commenter_name', 'route_name', 'route_id'],
                'icon' => 'comment',
                'color' => '#2196F3',
                'sound' => 'default',
            ],
            [
                'type' => 'route_warning',
                'name' => 'Route Warning',
                'description' => 'Sent when there is a warning on your route',
                'title_template' => '⚠️ Route Warning | تحذير على المسار',
                'message_template' => 'Warning on route "{{route_name}}": {{warning_text}} | تحذير على المسار "{{route_name}}": {{warning_text}}',
                'variables' => ['route_name', 'route_id', 'warning_text'],
                'icon' => 'warning',
                'color' => '#FF9800',
                'sound' => 'alert',
            ],

            // System
            [
                'type' => 'system_updates',
                'name' => 'System Update',
                'description' => 'Sent for system updates and announcements',
                'title_template' => '🔔 System Update | تحديث النظام',
                'message_template' => '{{update_title}}: {{update_message}} | {{update_title}}: {{update_message}}',
                'variables' => ['update_title', 'update_message'],
                'icon' => 'system_update',
                'color' => '#607D8B',
                'sound' => 'default',
            ],
            [
                'type' => 'promotional',
                'name' => 'Promotional',
                'description' => 'Sent for promotional offers',
                'title_template' => '🎁 Special Offer | عرض خاص',
                'message_template' => '{{promo_title}}: {{promo_message}} | {{promo_title}}: {{promo_message}}',
                'variables' => ['promo_title', 'promo_message', 'promo_url'],
                'icon' => 'local_offer',
                'color' => '#E91E63',
                'sound' => 'default',
            ],
            [
                'type' => 'newsletter',
                'name' => 'Newsletter',
                'description' => 'Sent for newsletter updates',
                'title_template' => '📧 Newsletter | النشرة الإخبارية',
                'message_template' => '{{newsletter_title}}: {{newsletter_preview}} | {{newsletter_title}}: {{newsletter_preview}}',
                'variables' => ['newsletter_title', 'newsletter_preview', 'newsletter_url'],
                'icon' => 'email',
                'color' => '#2196F3',
                'sound' => 'default',
            ],
            [
                'type' => 'admin_custom',
                'name' => 'Admin Custom Notification',
                'description' => 'Custom notification from admin',
                'title_template' => '{{custom_title}}',
                'message_template' => '{{custom_message}}',
                'variables' => ['custom_title', 'custom_message'],
                'icon' => 'notifications',
                'color' => '#FF6B6B',
                'sound' => 'default',
            ],
        ];

        foreach ($templates as $template) {
            NotificationTemplate::updateOrCreate(
                ['type' => $template['type']],
                $template
            );
        }
    }
}
